[profile.default]
src = 'contracts'
out = 'out'
test = 'test'
libs = ['node_modules', 'lib']
script = 'script'
cache_path = 'cache-forge'
gas_reports = ["*"]
via_ir = true
sizes = true
optimizer_runs=1000
solc_version = '0.8.19'
ffi = true

[fuzz]
runs = 10000

[invariant]
runs = 1000
depth = 30

[rpc_endpoints]
arbitrum = "${PROVIDER_42161}"
mainnet = "${PROVIDER_1}"
optimism = "${PROVIDER_10}"
polygon = "${PROVIDER_137}"

[etherscan]
arbitrum = { key = "${ARBITRUM_ETHERSCAN_API_KEY}" }
mainnet = { key = "${MAINNET_ETHERSCAN_API_KEY}" }
optimism = { key = "${OPTIMISM_ETHERSCAN_API_KEY}" }
polygon = { key = "${POLYGON_ETHERSCAN_API_KEY}" }


[profile.dev]
src = 'test'
via_ir = true
gas_reports = ["*"]

[profile.dev.fuzz]
runs = 100

[profile.dev.invariant]
runs = 10
depth = 30
fail_on_revert = false
